CLASS zcl_lab_40_actual_budget_fjcm DEFINITION INHERITING FROM zcl_lab_39_budget_fjcm
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS: get_budget REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_40_actual_budget_fjcm IMPLEMENTATION.

  METHOD get_budget.
  ENDMETHOD.

ENDCLASS.
