CLASS zcl_lab_12_linux_fjcm DEFINITION INHERITING FROM zcl_lab_11_system_fjcm
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_fjcm IMPLEMENTATION.
ENDCLASS.
