CLASS zcl_20_honda_crv_fjcm DEFINITION INHERITING FROM zcl_19_honda_fjcm
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
    METHODS set_model REDEFINITION.
    METHODS: set_max_speed REDEFINITION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_20_honda_crv_fjcm IMPLEMENTATION.

  METHOD set_max_speed.

  ENDMETHOD.

  METHOD set_model.

  ENDMETHOD.

ENDCLASS.
