CLASS zcl_21_airplane_fjcm DEFINITION ABSTRACT
  PUBLIC
"  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: airplane_type ABSTRACT RETURNING VALUE(rv_airline_type) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_21_airplane_fjcm IMPLEMENTATION.
ENDCLASS.
